// <auto-generated />
using System;
using ActivationWs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ActivationWs.Migrations
{
    [DbContext(typeof(ActivationDbContext))]
    [Migration("20250711194301_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("ActivationWs.Models.ActivationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfirmationID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtendedProductID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallationID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LicenseAcquisitionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MachineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MachineId", "InstallationID", "ExtendedProductID")
                        .IsUnique();

                    b.ToTable("ActivationRecords");
                });

            modelBuilder.Entity("ActivationWs.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("ActivationWs.Models.ActivationRecord", b =>
                {
                    b.HasOne("ActivationWs.Models.Machine", "Machine")
                        .WithMany("ActivationRecords")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("ActivationWs.Models.Machine", b =>
                {
                    b.Navigation("ActivationRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
